[project]
name = "comfyui-prompt-manager"
description = "A simple custom node for ComfyUI that allows you to save and reuse prompts, organized into different categories"
version = "1.1.0"

[project.urls]
Repository = "https://github.com/FranckyB/ComfyUI-Prompt-Manager"

[tool.comfy]
PublisherId = "FranckyB"
DisplayName = "ComfyUI-Prompt-Manager"
